from fpdf import FPDF
from datetime import datetime
import re


def _safe(text: str) -> str:
    """
    Convert text to latin-1 safe string.
    Replaces common unicode chars with ASCII equivalents,
    then drops anything still outside latin-1 range.
    """
    if not text:
        return ""
    replacements = {
        "\u2022": "-",   # bullet •
        "\u2013": "-",   # en dash
        "\u2014": "-",   # em dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2026": "...", # ellipsis
        "\u00b7": "-",   # middle dot
        "\u2212": "-",   # minus sign
        "\u00d7": "x",   # multiplication sign
        "\u00f7": "/",   # division sign
        "\u2192": "->",  # right arrow
        "\u2190": "<-",  # left arrow
        "\u2605": "*",   # star
        "\u25cf": "-",   # black circle
        "\u25a0": "-",   # black square
        "*":      "-",   # asterisk used as bullet
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Drop anything still outside latin-1
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class PDFService:
    @staticmethod
    def generate_note_pdf(note_data: dict, output_path: str) -> str:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(0, 12, _safe(note_data.get("title", "Voice Note")), ln=True, align="C")
        pdf.ln(4)

        # Metadata
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(107, 114, 128)
        created_at = note_data.get("created_at", datetime.now().strftime("%Y-%m-%d %H:%M"))
        source_type = note_data.get("source_type", "audio").replace("_", " ").title()
        duration = note_data.get("duration", 0)
        duration_str = f"{int(duration // 60)}m {int(duration % 60)}s" if duration else "N/A"
        pdf.cell(0, 6, f"Date: {created_at}  |  Source: {source_type}  |  Duration: {duration_str}", ln=True, align="C")
        pdf.ln(6)

        # Divider
        pdf.set_draw_color(229, 231, 235)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        # Keywords
        keywords = note_data.get("keywords", [])
        if keywords:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(17, 24, 39)
            pdf.cell(0, 8, "Keywords", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(99, 102, 241)
            pdf.multi_cell(0, 6, _safe("  -  ".join(keywords)))
            pdf.ln(4)

        # Summary
        summary = note_data.get("summary", "")
        if summary:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(17, 24, 39)
            pdf.cell(0, 8, "Summary", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(55, 65, 81)
            pdf.multi_cell(0, 6, _safe(summary))
            pdf.ln(4)

        # Full Transcript
        transcript = note_data.get("transcript", "")
        if transcript:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(17, 24, 39)
            pdf.cell(0, 8, "Full Transcript", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(75, 85, 99)
            pdf.multi_cell(0, 5, _safe(transcript))

        # Footer
        pdf.set_y(-15)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(156, 163, 175)
        pdf.cell(0, 10, "Generated by AI Voice Notes", align="C")

        pdf.output(output_path)
        return output_path
